# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Enable corepack
        run: corepack enable
      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'yarn'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: 'Do the build'
        run: yarn && yarn build
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: 'Upload dist as artifact'
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
          retention-days: 1

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: 'Node setup'
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://npm.pkg.github.com/
      - name: 'Fetch dist artifact from build'
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: 'List built content'   
        run: ls -R dist
      - name: 'Publish the package'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
